site_name: 'DR'
site_url: https://davideriboli.net
copyright: <a href="/colophon/">&#182; &#169;</a>

markdown_extensions: 
- md_in_html
- attr_list  
- tables
- meta
- pymdownx.highlight:
    use_pygments: true
    pygments_lang_class: true
    auto_title: true
    anchor_linenums: true
    linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.top
    - content.code.annotate
    - content.code.copy
  language: it
  logo: assets/logo/logo.png
  favicon: assets/logo/logo.png
  font:
    text: Poppins
    code: Source Code Pro
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Spegni la luce
      primary: blue grey
      accent: red
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Accendi la luce
      primary: blue grey
      accent: light blue

extra:
  consent:
    title: Biscottino?
    description:
      Il sito non profila in alcun modo e non richiede dati personali. I <i>cookie</i> sono usati solo per il conteggio visite e, se possibile, per il ripristino delle preferenze di lettura.
    actions:
     - accept
     # - reject 
  generator: false
  analytics:
    provider: google
    property: G-QT9PPLMPTW
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/davideriboli
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/DavideRiboli

extra_css:
  - stylesheets/extra.css

plugins:
  - social:
      cards_layout_options:
        background_color: #4c566a
  - blog:
      pagination_per_page: 7
      blog_dir: blog
      post_date_format: full
      post_url_format: "{date}/{slug}"
      post_excerpt: required
      archive_name: Annate
      categories_name: Scaffali
  - glightbox:
     touchNavigation: true
     loop: false
     effect: zoom
     slide_effect: slide
     width: 100%
     height: auto
     zoomable: true
     draggable: true
     skip_classes:
       - custom-skip-class-name
     auto_caption: true
     caption_position: bottom
  - search:
      lang: it

nav:
- Blog:
  - blog/index.md 
- Info:
  - info.md